name: hitbeat
description: beat box learning

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  modal_progress_hud: ^0.1.3
  flutter_audio_recorder: ^0.5.2
  path_provider:
  audioplayers:
  video_player:
  flutter_signin_button:
  http:
  shared_preferences:
  flutter_animation_progress_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf
        
    - family: Della_Respira
      fonts:
        - asset: fonts/DellaRespira-Regular.ttf

    - family: Rajdhani-Regular
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
  
  assets:
    - assets/